// Generated by CoffeeScript 1.9.2
describe('link parsing', function() {
  beforeEach(module('app'));
  beforeEach(inject(function(LinkParser) {
    this.linkParser = new LinkParser;
  }));
  return it('extracts Atom links', function() {
    var AtomResponse, extractedLinks;
    spyOn(this.linkParser, 'extractLinkedObjs').andCallThrough();
    AtomResponse = {
      links: [
        {
          href: "http://example.com",
          rel: "self"
        }
      ]
    };
    extractedLinks = [];
    this.linkParser.extractLinkedObjs(AtomResponse, extractedLinks);
    expect(this.linkParser.extractLinkedObjs).toHaveBeenCalled();
    return expect(extractedLinks.length).toBe(1);
  });
});
